UPPER_Y = 95
LEFT_X = 1904
LOWER_Y = 1049
RIGHT_X = 3424
FNAME_BASE = '一生使える見やすい資料のデザイン入門'
TEST_NUM = 3
# MODE = 'test'
MODE = 'trim'
CONVERT_TO_PDF = True
INPUT_DIR = '/mnt/c/work/プレゼン資料作り/一生使える見やすい資料のデザイン入門/キャプチャ'
FILES_LIST = '/mnt/c/work/プレゼン資料作り/一生使える見やすい資料のデザイン入門/キャプチャ/files.txt'
OUTPUT_DIR = '/mnt/c/work/プレゼン資料作り/一生使える見やすい資料のデザイン入門/trimmed'
