LEFT_X = 120
UPPER_Y = 95
RIGHT_X = 1847
LOWER_Y = 997
TITLE = '次世代プログラミング言語Juliaのすすめ_2'
PARENT_DIR = '/mnt/c/work/Julia'
FNAME_BASE = f'{TITLE}'
TEST_NUM = 3
# MODE = 'test'
MODE = 'trim'
CONVERT_TO_PDF = True
INPUT_DIR = f'{PARENT_DIR}/{TITLE}/img'
FILES_LIST = f'{PARENT_DIR}/{TITLE}/files.txt'
OUTPUT_DIR = f'{PARENT_DIR}/{TITLE}/trimmed'
